// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace COMP2001_Final.Models
{
    public partial class DisplayUserBadge
    {
        public string UserName { get; set; }
        public string BadgeName { get; set; }
        public string BadgeDescription { get; set; }
    }
}